### ISSUE TITLE
Compatibility with AspNetCore 3.0 Razor Components

### ISSUE THREAD

**Issue by khenzar** [Beffyman/AspNetCore.Client#65]
Hi Beffyman, this is an awesome project!
I am trying to get it up and running in Razor Components (equivalent to Balzor Server-side) which came in with AspNetCore 3.0 Preview.
I got stuck on configuring the serializers.

I followed your instructions, but I am getting the following error at runtime, when the client class gets injected. 
`System.InvalidOperationException  "Cannot resolve scoped service 'AspNetCore.Client.Serializers.BlazorSimpleJsonSerializer' from root provider."`
on line `Serializer = param_serializer(this);` in the constructor of the generated client class.
 
I am guessing this has something to do with how HttpClient is injected in Server-side Blazor.
You could argue that using Web API and HttpClient in Server-side Blazor doesn't make sense, since you can directly reference the repository/persistence layer, however it makes sense from the future perspective of code separation and possibility to easily migrate the project to Client-Side Blazor when it gets less experimental.

So, do you have any plans of checking the compatibility with this platform? 
Thanks for any answer!

Best regards, Ondrej

**Comment by Beffyman** [comment]
I haven't checked out Razor Components yet, but from that error message maybe it is having an issue resolving it because a scope is never setup inside the ServiceProvider (guessing)?  I'll investigate this, as I do want to support the official Blazor.

**Comment by Beffyman** [comment]
@khenzar If you use the AspNetCore.Client.JSInterop package instead of AspNetCore.Client.BlazorJson it should work now, or at least I was able to get it working.

**Comment by khenzar** [comment]
> 
> 
> @khenzar If you use the AspNetCore.Client.JSInterop package instead of AspNetCore.Client.BlazorJson it should work now, or at least I was able to get it working.

I will try this today and let you know.
